[workspace]
authors = ["JoelStansbury <stansbury.joel@gmail.com>"]
channels = ["conda-forge"]
name = "twig"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
code = "code ."
gen-key = {cmd = "openssl rand -hex 32 >> secret", outputs = ["secret"]}
create-db = "python scripts/db-init.py -n twig"
create-test-db = "python scripts/db-init.py -n testdb --delete"
lab = "jupyter lab"

# Linting
-ruff-fix = "ruff check src tests --fix"
-ruff-check = "ruff check src tests"

[tasks.fix]
depends-on = ['-ruff-fix']
[tasks.lint]
depends-on = ['-ruff-check']


[tasks.start] 
cmd = "python -m twig"
depends-on = ["gen-key", "create-db"]
env = { DATABASE_URL="postgresql+psycopg2:///twig" }

[tasks.test] 
cmd = "pytest"
depends-on = ["gen-key", "create-test-db"]
env = { DATABASE_URL="postgresql+psycopg2:///testdb" }

[environments]
default = ["dev"]

[pypi-dependencies]
twig = {path=".", editable = true}

[dependencies]
# Database
postgresql = "*"
psycopg2 = "*"
# Python
python = ">=3.14"
jsonpointer = "*"
# Server
fastapi = "*"
pydantic = "*"
sqlmodel = "*"
uvicorn = "*"
# Cryptography (Password Management)
argon2-cffi = "*"
pwdlib = "*"
pyjwt = "*"

[feature.dev.dependencies]
pytest = "*"
pytest-html = "*"
pytest-cov = "*"
pytest-timeout = "*"
mypy = "*"
ruff = "*"
types-psutil = "*"
httpx2 = "*"
jupyterlab = "*"
networkx = "*"